name: Deploy

on:
  push:
    branch: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh -l ${{ secrets.SSH_USER }} ${{ secrets.SERVER_IP }} << 'EOF'
          cd CurDRF/
          git pull
          echo '"${{ secrets.ENV_FILE }}"' | sed "s/\"//g" > .env
          exit
          EOF
